name: Install Tailscale, Open RDP Port, and Set Username/Password

on:
  push:
    branches:
      - main

jobs:
  install-tailscale:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set Execution Policy to Bypass
      shell: powershell
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force

    - name: Download Tailscale Installer
      shell: powershell
      run: |
        Invoke-WebRequest -Uri https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe -OutFile tailscale-setup.exe

    - name: Install Tailscale
      shell: powershell
      run: |
        Start-Process -FilePath .\tailscale-setup.exe -ArgumentList "/quiet", "/norestart" -Wait

    - name: Open RDP Port 3389
      shell: powershell
      run: |
        New-NetFirewallRule -DisplayName "Allow RDP" -Direction Inbound -Protocol TCP -Action Allow -LocalPort 3389

    - name: Enable RDP on Windows
      shell: powershell
      run: |
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Create Administrator Account if Not Exists
      shell: powershell
      run: |
        # Set username and password
        $username = "administrator"  # Using 'administrator' with lowercase 'a'
        $password = ConvertTo-SecureString "Budeaxasb13" -AsPlainText -Force
        $credential = New-Object System.Management.Automation.PSCredential ($username, $password)

        # Check if administrator account exists
        $adminUser = Get-LocalUser -Name $username -ErrorAction SilentlyContinue
        if ($adminUser) {
          Write-Host "Administrator account exists, setting password."
          Set-LocalUser -Name $username -Password $password
        } else {
          Write-Host "Administrator account not found. Creating new administrator account."
          # Create administrator account if not exists
          New-LocalUser -Name $username -Password $password -FullName "Administrator" -Description "Local Administrator Account"
          Add-LocalGroupMember -Group "Administrators" -Member $username
        }

        # Enable the administrator account if it's disabled
        Enable-LocalUser -Name $username

    - name: Start Tailscale
      shell: powershell
      run: |
        Start-Process "C:\Program Files\Tailscale\tailscale.exe" -ArgumentList "up", "--authkey", "${{ secrets.TAILSCALE_AUTHKEY }}" -Wait

    - name: Get Tailscale IP
      shell: powershell
      run: |
        # Retrieve the Tailscale IP
        $tailscaleIp = & "C:\Program Files\Tailscale\tailscale.exe" ip -4
        Write-Host "Tailscale IP: $tailscaleIp"