name: Install and Configure Tailscale

on:
  push:
    branches:
      - main

jobs:
  install-tailscale:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set Execution Policy to Bypass
      shell: powershell
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force

    - name: Download Tailscale Installer
      shell: powershell
      run: |
        Invoke-WebRequest -Uri https://pkgs.tailscale.com/stable/tailscale-setup.exe -OutFile tailscale-setup.exe

    - name: Install Tailscale
      shell: powershell
      run: |
        Start-Process -FilePath .\tailscale-setup.exe -ArgumentList "/quiet", "/norestart" -Wait

    - name: Start Tailscale
      shell: powershell
      run: |
        "C:\Program Files\Tailscale\tailscale.exe" up --authkey "${{ secrets.TAILSCALE_AUTHKEY }}"